name: PR Auto-merge

on: repository_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Trigger pr-autobuild action
        uses: tivoyudhap/to-do-list-composable-android@master
        env:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          GITHUB_NAME: tivoyudhap
          DEFAULT_APPROVAL_COUNT_ENV: 1
          BUILD_COMMENT_ENV: "OK to test"
          PR_LABEL_ENV: RELEASE
          DELETE_BRANCH_ENV: true
