name: PR Auto-build

on:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Trigger pr-autobuild action for building PR
        uses: tivoyudhap/to-do-list-composable-android@master
        env:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          GITHUB_NAME: tivoyudhap
          DEFAULT_APPROVAL_COUNT_ENV: 1
          BUILD_COMMENT_ENV: "OK to test"
          PR_LABEL_ENV: RELEASE_TEST
          CODEOWNERS: tivo.yudhap11@gmail.com
